apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: emp-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: i222473/employee-backend:latest
        imagePullPolicy: Never  
        ports:
        - containerPort: 5000