name: Build and Deploy to Kubernetes

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        try {
          & minikube -p minikube docker-env --shell powershell | Invoke-Expression
          echo "✅ Docker configured to use Minikube's daemon"
        } catch {
          echo "❌ Error configuring Docker: $_"
          # Continue anyway and don't fail the build
          # exit 1
        }
    
    - name: Build Backend
      run: |
        echo "Building backend Docker image..."
        cd app/backend
        try {
          docker build -t employee-backend:latest .
          echo "✅ Backend Docker image built successfully"
        } catch {
          echo "❌ Error building backend Docker image: $_"
          exit 1
        }
    
    - name: Build Frontend
      run: |
        echo "Building frontend Docker image..."
        cd app/frontend
        try {
          docker build -t employee-frontend:latest .
          echo "✅ Frontend Docker image built successfully"
        } catch {
          echo "❌ Error building frontend Docker image: $_"
          exit 1
        }
    
    - name: Deploy to Kubernetes
      if: github.event_name == 'push'
      run: |
        echo "Deploying to Kubernetes..."
        try {
          kubectl apply -f kubernetes/namespace.yaml
          kubectl apply -f kubernetes/backend-deployment.yaml -n emp-management
          kubectl apply -f kubernetes/frontend-deployment.yaml -n emp-management
          kubectl apply -f kubernetes/backend-service.yaml -n emp-management
          kubectl apply -f kubernetes/frontend-service.yaml -n emp-management
          echo "✅ Deployed to Kubernetes successfully"
        } catch {
          echo "❌ Error deploying to Kubernetes: $_"
          exit 1
        }
    
    - name: Verify Deployment
      if: github.event_name == 'push'
      run: |
        echo "Verifying deployment..."
        try {
          kubectl get pods -n emp-management
          kubectl get services -n emp-management
          echo "✅ Deployment verification completed"
        } catch {
          echo "❌ Error verifying deployment: $_"
          # Continue anyway and don't fail the build
          # exit 1
        }